name: build-pipeline
run-name: ${{ github.repository }} build pipeline
on:
  workflow_dispatch:
    inputs:
      build-push-image:
        type: boolean
        description: Build and Push the Image
  push:
    branches:    
      - '*'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo ${{ github.ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: '14.15.4'
      - run: npm ci
        working-directory: ./src
      - run: npm run build
        working-directory: ./src
      # - run: npm run test
  image:
    if: 
      ${{ github.ref == refs/heads/release/* }} || 
      ${{ github.ref == refs/heads/hotfix/* }}  || 
      github.event.build-push-image == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker image build . 
        working-directory: ./src