name: deploy-pipeline
run-name: ${{ github.repository }} deploy pipeline
on:
  workflow_dispatch:
    inputs:
      image-tag:
        type: string
        description: Image Tag

env:
  IMAGE_HOST: ghcr.io
  IMAGE_PATH: ${{ github.repository }}
  IMAGE_TAG: ${{ github.event.inputs.image-tag }}
  APP_NAME: ${{ github.event.repository.name }}
  HELM_CHART: ./rhos-nodejs-0.0.1.tgz

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: checkout helm repo
        with:
          repository: IntegrationWorks/helm-packaged-charts
          token: ${{ secrets.HELM_READ_ACCESS_TOKEN }} 

      - id: lower-case-vars
        run: |
          image_full=${{ env.IMAGE_HOST }}/${{ env.IMAGE_PATH }}
          app=${{ env.APP_NAME }}
          echo "image=${image_path,,}" >> $GITHUB_OUTPUT
          echo "release_name=${app,,}" >> $GITHUB_OUTPUT

      - name: Install oc
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: 4

      - name: OpenShift login
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ vars.IW_OPENSHIFT_SERVER_NON_PROD }}
          openshift_token: ${{ secrets.IW_OPENSHIFT_TOKEN_NON_PROD }}
          insecure_skip_tls_verify: true
          namespace: ${{ vars.IW_OPENSHIFT_NAMESPACE_DEV }}

      - name: Deploy
        run: |
          helm upgrade -i \
          ${{ steps.lower-case-vars.outputs.release_name  }} ${{ env.HELM_CHART }} \
          --set image.name=${{ steps.lower-case-vars.outputs.image }} \
          --set image.tag=${{ env.IMAGE_TAG }} --wait